#!/usr/bin/env bash
# Produces tfplan and tfplan.json with mock credentials and no AWS account.
#
# Two things this has to work around, both measured rather than assumed:
#
# 1. `terraform init -backend=false` is enough for `validate` and NOT enough for
#    `plan`: with a backend block declared, plan answers "Backend
#    initialization required". So the offline plan runs against a local backend
#    supplied by an override file, which is a documented Terraform mechanism and
#    is git-ignored. The committed configuration still declares the real S3
#    backend.
# 2. The provider's skip_* flags suppress validation calls, not credential
#    *resolution*. With no AWS_ACCESS_KEY_ID at all, plan fails with "failed to
#    refresh cached credentials, no EC2 IMDS role found". The dummy values below
#    are load-bearing.
#
# The plan file and the JSON both hold every secret this stack has, in
# cleartext. They stay on the runner: never an artifact, never a log line.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

# TEST-NET-3. A documentation range rather than 0.0.0.0/0, so that the offline
# plan is not itself an example of the thing the policy suite refuses.
ALB_CIDRS=${ALB_CIDRS:-'["203.0.113.0/24"]'}
DB_PASSWORD=${TF_VAR_db_password:-offline-plan-not-a-credential}
# A placeholder that could not be a real registry, so an offline plan is never
# mistaken for a deployable one. deploy.yml passes the real value.
IMAGE_REGISTRY=${IMAGE_REGISTRY:-registry.invalid/codetrail}

cat > backend_override.tf <<'HCL'
# Generated by offline_plan.sh; git-ignored. See the header there for why.
terraform {
  backend "local" {}
}
HCL

# Removed before planning, not after: a plan that fails leaves the previous
# JSON on disk, and the policy suite would then assert over a stale artifact and
# report ok. Measured while running C7.
rm -f tfplan tfplan.json

export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-mock}
export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-mock}
export AWS_REGION=${AWS_REGION:-us-east-1}
export TF_VAR_db_password=$DB_PASSWORD

terraform init -input=false -reconfigure >/dev/null
terraform plan -input=false -lock=false \
	-var "alb_allowed_cidrs=$ALB_CIDRS" \
	-var "image_registry=$IMAGE_REGISTRY" \
	-out=tfplan >/dev/null
terraform show -json tfplan > tfplan.json
echo "wrote infra/terraform/tfplan.json"
